### ISSUE TITLE
[Feature Request] Restore backups which were dumped

### ISSUE THREAD

**Issue by asittampalam** [swisscom/backman#11]
Hi @JamesClonk 

First of all, thanks for your work. 
Is it possible to add a possibility to restore downloaded backups via the UI? Would be perfect!

**Comment by JamesClonk** [comment]
Hi @asittampalam,
There should already be a restore button on the UI?

**Comment by asittampalam** [comment]
@JamesClonk  Sorry, I probably wasn't precise enough: I'm talking about dumps which were downloaded to the local storage (not S3). It would be nice, if there was a possibility to upload those and restore them.

**Comment by JamesClonk** [comment]
Ah ok, I see.

You could just upload the dump onto S3 into the correct bucket/folder where backman reads from. It would then be displayed as well on the service view and have the restore button present. :smiley:

**Comment by asittampalam** [comment]
@JamesClonk - True, maybe building that feature would be a bit overkill :)
