### ISSUE TITLE
mysql as a user-defined service

### ISSUE THREAD

**Issue by crypticro** [swisscom/backman#13]
Is there a way to configure a mysql service as user-defined service as it works for postgres?

**Comment by JamesClonk** [comment]
@crypticro No, currently backman so far only parses postgres connection strings in a user-provided service.
I'm running backman myself on the Swisscom AppCloud / CF, where there is a mysql service provided from the marketplace itself, so I had no use yet myself for a mysql user-provided service binding.
But it would definitely be possible to add it to backman if necessary.
I could add it if you think it's needed?

**Comment by crypticro** [comment]
@JamesClonk I am using the internal AppCloud but our MySQL servers are not in the cloud but on dedicated servers. That's why it would be very useful for us. So yeah it would be appreciated :-)

**Comment by JamesClonk** [comment]
@crypticro OK I see.
I've added some basic detection of MySQL user-provided service bindings to the latest version. 

The binding will need to contain at least a DB URI to be detected and parsed correctly. 
Here's an iAPC MySQL example binding for reference:
```
    "credentials": {
     "database": "my_database_name",
     "database_uri": "mysql://my_username:my_password@my_hostname:3306/my_database_name?reconnect=true",
     "host": "my_hostname:3306",
     "hostname": "my_hostname",
     "jdbcUrl": "jdbc:mysql://my_hostname:3306/my_database_name?user=my_username\u0026password=my_password",
     "name": "my_database_name",
     "password": "my_password",
     "port": 3306,
     "uri": "mysql://my_username:my_password@my_hostname:3306/my_database_name?reconnect=true",
     "username": "my_username"
    }
```
Out of these backman requires at least `database_uri`, `jdbcUrl` or `uri` to properly detect the service.

**Comment by crypticro** [comment]
@JamesClonk  Thanks for that quick change! works perfectly.
