### ISSUE TITLE
Ignore time zone declaration in filepath

### ISSUE THREAD

**Issue by meyerf99** [swisscom/backman#14]
Hello @JamesClonk 

I'm using your backman Docker repo on Swisscom Cloud Foundry for backing up MongoDB's.
Now I noticed that the backup filename does not use the correct time zone, which was defined when deploying the application by setting "cf set-env backman TZ Europe/Zurich".

![swisscom_cf_backman_timezone](https://user-images.githubusercontent.com/28959963/69254941-43a48e80-0bb7-11ea-9709-be9b9e0a77bf.png)

backman uses the time zone UTC which is shown in the filename.

Is this a bug of the application or am I setting the time zone of the backmann app wrong?

Thanks for your help :)

Regards,
Flavio

**Comment by JamesClonk** [comment]
Hi @meyerf99,

Thanks for the hint, it's indeed a bug. 
It seems I forgot to add the `tzdata`package to the Docker image, so it was not respecting (or rather simply not working with) the TZ env variable.
I just built and pushed a new image that also contains the necessary tzdata, now it should work. :smile: :+1:
