### ISSUE TITLE
[Feature Request] Add support for Redis and Redis Enterprise

### ISSUE THREAD

**Issue by sebastianhaeni** [swisscom/backman#16]
It would be nice to have Redis and/or Redis Enterprise as a supported data source.

**Comment by JamesClonk** [comment]
My Redis knowledge is very limited, but as far as I know unfortunately Redis seems to not be very remote-backup friendly. There are a couple of hacks out there I found, but I'm not sure I'd trust them to produce proper backup data. (redis-dump, redis-dump-go, etc..)

It seems Redis backups are commonly done locally on the Redis host itself, which is something backman cannot do obviously. The only thing I found was using `redis-cli` with `--rdb`, but unfortunately this writes into a local file, inside the backman app container. I cannot pipe it directly onto S3.
@sebastianhaeni If that's fine for you I could try to add it to backman?
It would simply mean that Redis backups will first have to be fully written temporarily into the app containers filesystem and consume space there, so very large backups might not work.

**Comment by sebastianhaeni** [comment]
Yes, that sounds fine using the RDB file. It's also mentioned that this would be the preferred way to backup Redis data in the Redis docs.

I also don't know of any other practical solution to back up Redis data without writing to a file locally except building your own backup scripts. E.g. you could read every key with `KEYS *`, then read the values with `MGET {keys}` and write the key with the value into a text based file with a custom format. Or you could even use `SCAN` to do it incrementally without blocking other operations.

But that is too errorprone if you ask me and RDB should just be fine.

**Comment by batigoal82** [comment]
I guess the idea with redis-cli is not really nice for a generic redis backup solution. I would say a better idea would be as Sebastian noted to use SCAN command and use a cursor to get the keys and then to use redis dump command to get a serialized version of the value for each key.  There are some redis go libraries which can be used to connect to remote redis and issue commands like for example ["Go Redis"](https://github.com/go-redis/redis). Also, for restore, the RESTORE command could be used giving a key and the dumped value.

**Comment by JamesClonk** [comment]
I've added some rudimentary Redis backup support via `redis-cli --rdb` now. As mentioned it will dump the file locally inside the container and then upload it onto S3.
Unfortunately going the rdb route means backman has no support for restoring Redis backups, as that needs to be done manually on the Redis instance by an admin.

Feel free to submit PRs though if you feel like improving on it, or switching to a more custom SCAN/RESTORE commands solution. I simply didn't feel comfortable enough myself to directly interact with Redis, I've never really used it for anything serious myself as a data store. 😅

**Comment by sebastianhaeni** [comment]
Awesome! Thanks. Maybe we'll follow up with a PR.
