### ISSUE TITLE
[Feature Request] Add an option to run backup/restore via CloudFoundry Tasks

### ISSUE THREAD

**Issue by vlev** [swisscom/backman#18]
It would be great to be able to trigger backups/restore via [CF Tasks](http://v3-apidocs.cloudfoundry.org/version/3.0.0/index.html#the-task-object)

This way we could rollout backman with 0 instances, making the solution a bit more cost effective.
Plus, this way we could run multiple operations in parallel without the risk of running out of resources or facing concurrency related issues.

**Comment by r-chris** [comment]
This would probably be easy if we could provide more customizations to the `cf task`, but I assume that's not going to happen.

You could of course also use the AutoScaler that is available within the Swisscom AppCloud and schedule your instance to be at 0 for most of the day and only up and running during a specific time interval, when you want to run your backups:

https://ict.swisscom.ch/2018/12/automagically-scale-your-apps-on-cloud-foundry/

Of course that doesn't solve the concurrency questions.

**Comment by JamesClonk** [comment]
I've added the option to run specific backups/restores as backman command line arguments:
`backman -backup <service>`
`backman -restore <service> -filename <filename>`
This should allow it to be used as a CF task.

**Comment by r-chris** [comment]
@JamesClonk I testes this today. I am using the docker container at the moment and wanted to report that you have to specify the full path to the `backman` executable for the task to start. 

Example:

`cf run-task backman-app "backman -backup some-db-service"`

Results in:

`ERR /bin/sh: 1: backman: not found`

So, I am using:

`cf run-task backman-app "/app/backman -backup some-db-service"`

**Comment by JamesClonk** [comment]
@r-chris I've clarified the path in the readme now, thanks!
