### ISSUE TITLE
Elasticdump refuses to dump?

### ISSUE THREAD

**Issue by mischaduebendorfer** [swisscom/backman#21]
Hi @JamesClonk ,

If I trigger a backup in the Backman UI I can see the elasticdump process in the container.
But there is no data written to S3.

Now, if I copy the elasticdump command from ps x and execute it directly in the shell I can see the output from elasticsearch written to stdout. (with --output=$)

Replacing the below elasticdump command with 'echo foo' I can see data being written to S3.
So it seems that elasticdump does not print to stdout so backman can process it.

```
command = append(command, "elasticdump")
command = append(command, "--quiet")
command = append(command, fmt.Sprintf("--input=%s", connectstring))
command = append(command, "--output=$")
log.Debugf("executing elasticsearch backup command: %v", strings.Join(command, " "))
cmd := exec.CommandContext(ctx, command[0], command[1:]...)

// capture stdout to pass to gzipping buffer
outPipe, err := cmd.StdoutPipe()
```

Also pinned the version to 6.11.0 and older in the hope that the issue lies there but no success.
`RUN npm install elasticdump@6.26.0 -g`

Cheers,
Mischa

**Comment by mischaduebendorfer** [comment]
duplicate

**Comment by andreatera** [comment]
related to https://github.com/swisscom/backman/issues/15
