### ISSUE TITLE
Restore of other database

### ISSUE THREAD

**Issue by somehowchris** [swisscom/backman#24]
It would be nice to have the functionality to restore but from another backend from another database as we encounter numerous database change like from mariadb to mysql and from dedicated mongodb instances to mongodb ent databases and moving those backup files for over 50 databases is a pure pain in the ass

**Comment by somehowchris** [comment]
@JamesClonk #29 and #28 make it possible for mongodb and mysql

**Comment by JamesClonk** [comment]
Hey @somehowchris 
Thanks a lot for your PRs, nice work! 😃👍
