### ISSUE TITLE
[Bug] Mysqldump failing due to unknown table 'COLUMN_STATISTICS' in information_schema

### ISSUE THREAD

**Issue by seinol** [swisscom/backman#34]
Since upgrading from version v1.15.0 to v1.18.0, the mysql db backups(mariadb and mysql) are not working anymore, because of the following error:
`OUT level=error msg="mysqldump: Couldn't execute 'SELECT COLUMN_NAME, JSON_EXTRACT(HISTOGRAM, '$.\"number-of-buckets-specified\"') FROM information_schema.COLUMN_STATISTICS WHERE SCHEMA_NAME = 'CFDB_02C85CC4_2FF3_4535_BFC0_F2DDC7D79429' AND TABLE_NAME = 'answers';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)"`

The solution might be adding the option `--column-statistics=0` to the mysqldumps. (Source: https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109).

**Comment by somehowchris** [comment]
Solved in: [f8e177a37606fdd11045901e158ab8ee8fe7a8e0](https://github.com/swisscom/backman/commit/f8e177a37606fdd11045901e158ab8ee8fe7a8e0)
