### ISSUE TITLE
v1.23 doesn't start

### ISSUE THREAD

**Issue by janekolszak** [swisscom/backman#39]
I tried to start backman, but it crashes with error:

**./backman: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./backman)**

**Comment by JamesClonk** [comment]
Hi @janekolszak
This has been fixed in [v1.23.1](https://github.com/swisscom/backman/releases/tag/v1.23.1).

Cheers!
