### ISSUE TITLE
Possible vulnerability because of encryption key reusage

### ISSUE THREAD

**Issue by izolight** [swisscom/backman#41]
The used client side encryption is only secure if different encryption keys are used for each data stream(which at the current implementation means every file uploaded to s3)
https://github.com/minio/sio/blob/master/DARE.md
As per the documentation an attacker could do the following if the encryption key is reused:
- replace packets with the same sequence number (replace part of one file with part of another file)
- if the nonce is reused (which is 64bits, so becomes increasingly likely to be reused over many files and upload sessions), the attacker could decrypt the package

I would suggest to use the configured encryption key only as a master key to derive the actual encryption key for each file.
This could be accomplished by using a KDF with the master key and s3 object key (filename) as input. Although the recommendation is to not use the filename in case a new version is uploaded and thus resulting in the same key, i think this probably doesn't apply here as the filename contains a timestamp and is thus unique.

This change (with the key derived from filename) could be done relatively easy by just doing adjustments in the upload/download methods as no further key management is necessary.

**Comment by JamesClonk** [comment]
Hi @izolight 
I've changed the encryption key to be derived as per your suggestion.
Check out v1.24.0.

Cheers! :+1:

**Comment by izolight** [comment]
fixed via multiple PR
