### ISSUE TITLE
DB Restore with specific file on API

### ISSUE THREAD

**Issue by cawena** [swisscom/backman#48]
Backman version 1.27.0

it's not possible to restore a specific backup.
The API should provide /{file name} as parameter.

![image](https://user-images.githubusercontent.com/15812993/114707743-def94f00-9d2a-11eb-91d9-39299e855613.png)

Thats right now not possible.

**Comment by cawena** [comment]
OK, looks that is working with file..
but swagger is not documenting that.

**Comment by cawena** [comment]
It would be nice to see wich file was restored.

{
    "Service": {
        "Name": "........-mongo",
        "Label": "mongodbent",
        "Plan": "xxxsmall3rs",
        "Tags": [
            "mongodb"
        ],
        "Timeout": 3600000000000,
        "Schedule": "0 0 0 * * *",
        "Retention": {
            "Days": 31,
            "Files": 100
        },
        "DisableColumnStatistics": false,
        "ForceImport": false,
        "LocalBackupPath": "",
        "BackupOptions": null,
        "RestoreOptions": null
    },
    "Operation": "restore",
    "Status": "success",
    "At": "2021-04-14T14:12:05.872948097+02:00",
    "Duration": 6071969373
}

**Comment by JamesClonk** [comment]
Thanks for the hint, I forgot about adding {filename} and updating the Swagger doc.
I've also added `filename` to the `state` API responses.

Cheers!
