### ISSUE TITLE
Wrong Elasticsearch host produce: "Error Emitted => getaddrinfo ENOTFOUND"

### ISSUE THREAD

**Issue by andreatera** [swisscom/backman#59]
I installed backman `v1.30.1` in our internal Swisscom iAPC on multiple spaces/orgs.
Installation/Configuration is exactly the same for everyone but on some we get the following error after starting the backup of our elasticsearch service: `Error Emitted => getaddrinfo ENOTFOUND ikjwdvgadry9g9w`

Following the entire log:

> 2022-01-19 08:01:02 [APP/PROC/WEB/0] OUT level=debug msg="executing elasticsearch backup command: elasticdump --quiet --input=https://ikJWDVGAdry9g9WU:qD[1;A4,Jd?XK[qd@***************.elasticsearch.dev-scapp-console.swisscom.com:443 --output=$"
> 2022-01-19 08:01:02 [APP/PROC/WEB/0] OUT level=debug msg="upload S3 object [elasticsearch/elasticsearch-log/elasticsearch-log_20220119080102.gz]"
> 2022-01-19 08:01:25 [APP/PROC/WEB/0] OUT level=error msg="Wed, 19 Jan 2022 07:01:25 GMT | Error Emitted => getaddrinfo ENOTFOUND ikjwdvgadry9g9wu\nWed, 19 Jan 2022 07:01:25 GMT | Error Emitted => getaddrinfo ENOTFOUND ikjwdvgadry9g9wu"
> 2022-01-19 08:01:25 [APP/PROC/WEB/0] OUT level=error msg="could not backup service [elasticsearch-log]: elasticdump: exit status 1"
> 2022-01-19 08:01:25 [APP/PROC/WEB/0] OUT level=error msg="requested backup for service [elasticsearch-log] failed: elasticdump: exit status 1"
> 2022-01-19 08:01:25 [APP/PROC/WEB/0] OUT level=error msg="could not upload service backup [elasticsearch-log] to S3: context canceled"

**Comment by JamesClonk** [comment]
See comment in https://github.com/swisscom/backman/issues/60
