### ISSUE TITLE
Wrong Elasticsearch host produce: "Error Emitted => URI malformed"

### ISSUE THREAD

**Issue by andreatera** [swisscom/backman#60]
Same as https://github.com/swisscom/backman/issues/59 but with a different error message:

> 2022-01-19 08:24:51 [APP/PROC/WEB/0] OUT level=debug msg="executing elasticsearch backup command: elasticdump --quiet --input=https://shbfBNDYNTEpHEXy:6Vrz%+sMcPbbzcUm@***************.elasticsearch.dev-scapp-console.swisscom.com:443 --output=$"
> 2022-01-19 08:24:51 [APP/PROC/WEB/0] OUT level=debug msg="upload S3 object [elasticsearch/elasticsearch-log/elasticsearch-log_20220119082451.gz]"
> 2022-01-19 08:24:54 [APP/PROC/WEB/0] OUT level=error msg="Wed, 19 Jan 2022 07:24:54 GMT | Error Emitted => URI malformed\nWed, 19 Jan 2022 07:24:54 GMT | Error Emitted => URI malformed"
> 2022-01-19 08:24:54 [APP/PROC/WEB/0] OUT level=error msg="could not backup service [elasticsearch-log]: elasticdump: exit status 1"
> 2022-01-19 08:24:54 [APP/PROC/WEB/0] OUT level=error msg="requested backup for service [elasticsearch-log] failed: elasticdump: exit status 1"
> 2022-01-19 08:24:54 [APP/PROC/WEB/0] OUT level=error msg="could not upload service backup [elasticsearch-log] to S3: context canceled"

**Comment by JamesClonk** [comment]
Hi @andreatera 
It is likely this is happening because of the username/password you are using in your elasticsearch connection. It looks like they contain characters which break the --input URL.
I've added a small change to backman which will URLescape these two and should hopefully fix your issue: https://github.com/swisscom/backman/releases/tag/v1.30.2

**Comment by andreatera** [comment]
Thanks @JamesClonk now I'll try out..
Question about this username/password, where are these taken? Because are not the one we have in our service key of the elastic search service in iAPC.

**Comment by JamesClonk** [comment]
You can see what credential parameters it takes here:
https://github.com/swisscom/backman/blob/79495cd44b9c9eb28b8e120e14885085e0e70b5e/service/elasticsearch/backup.go#L35-L42

It tries `full_access_username` and `full_access_password` first by default, and falls back to just `username` and/or `password` if the former are not present within the elasticsearch binding.

**Comment by andreatera** [comment]
Ah ok perfect, and could be that are then encrypted when are logged? Because, as said, are not the same as we have (full_access_*).
Sorry if I bother you but I'm not so quick to read go code 😜

**Comment by andreatera** [comment]
Still not correct, on one instance I had following error:

> 2022-01-20 18:10:08 [APP/PROC/WEB/0] OUT level=error msg="Thu, 20 Jan 2022 17:10:08 GMT | Error Emitted => {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"unable to authenticate user [fsIYslBm2kQKpiFS] for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Bearer realm=\\\"security\\\"\",\"ApiKey\",\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"]}}],\"type\":\"security_exception\",\"reason\":\"unable to authenticate user [fsIYslBm2kQKpiFS] for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Bearer realm=\\\"security\\\"\",\"ApiKey\",\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"]}},\"status\":401}\nThu, 20 Jan 2022 17:10:08 GMT | Error Emitted => {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"unable to authenticate user [fsIYslBm2kQKpiFS] for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Bearer realm=\\\"security\\\"\",\"ApiKey\",\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"]}}],\"type\":\"security_exception\",\"reason\":\"unable to authenticate user [fsIYslBm2kQKpiFS] for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Bearer realm=\\\"security\\\"\",\"ApiKey\",\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"]}},\"status\":401}"

where the credentials are:
```
"full_access_username": "fsIYslBm2kQKpiFS",
"full_access_password": "7whs?D0*0&v{D%f7"
```

Still some special chars are not escaped correctly..

**Comment by JamesClonk** [comment]
This should be fixed now hopefully, I've changed to using `PathEscape` for the Elasticsearch credentials: https://github.com/swisscom/backman/releases/tag/v1.30.3
