### ISSUE TITLE
Add a triggered backup history of the service in the UI

### ISSUE THREAD

**Issue by andreatera** [swisscom/backman#62]
In order to retrieve easily the history of the triggered backup would be useful to have a this information in the UI in the service under backup with the followin infos:
- date-time started
- how long it took
- status (SUCCESS/FAILURE)
- error message (in case of FAILURE)

**Comment by JamesClonk** [comment]
This is unfortunately not really possible, as backman is stateless and does not have any backend database on its own. It would only be able to show recent things still in the app memory until the next restart and thus be rather unreliable.
