### ISSUE TITLE
elasticdump fails

### ISSUE THREAD

**Issue by eldom9** [swisscom/backman#75]
Using v2.0.0 and v2.0.1 of backman on iAPC -  elastic service backup always fails with the following errors:
```
10/27/2022, 11:47:06 PM [APP/PROC/WEB/0] OUT level=error msg="could not run elasticdump: exit status 1"
10/27/2022, 11:47:06 PM [APP/PROC/WEB/0] OUT level=error msg="could not backup service [cadc-elastic]: elasticdump: exit status 1"
10/27/2022, 11:47:06 PM [APP/PROC/WEB/0] OUT level=error msg="requested backup for service [cadc-elastic] failed: elasticdump: exit status 1"
```

**Comment by JamesClonk** [comment]
@eldom9 I found a bug when parsing elasticsearch bindings and created a new release that hopefully might fix your issues: https://github.com/swisscom/backman/releases/tag/v2.0.2
